<?php
/**
 * DsBusinessTrailEntryResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ProfileService\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProfileService-TEST
 *
 * Profile service test
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ProfileService\Client;

/**
 * DsBusinessTrailEntryResponseTest Class Doc Comment
 *
 * @category    Class
 * @description DsBusinessTrailEntryResponse
 * @package     ProfileService\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DsBusinessTrailEntryResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DsBusinessTrailEntryResponse"
     */
    public function testDsBusinessTrailEntryResponse()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "partner_acronym"
     */
    public function testPropertyPartnerAcronym()
    {
    }

    /**
     * Test attribute "level"
     */
    public function testPropertyLevel()
    {
    }

    /**
     * Test attribute "origin"
     */
    public function testPropertyOrigin()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "object_name"
     */
    public function testPropertyObjectName()
    {
    }

    /**
     * Test attribute "object_key"
     */
    public function testPropertyObjectKey()
    {
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
    }

    /**
     * Test attribute "event"
     */
    public function testPropertyEvent()
    {
    }

    /**
     * Test attribute "term_code"
     */
    public function testPropertyTermCode()
    {
    }

    /**
     * Test attribute "term_version_code"
     */
    public function testPropertyTermVersionCode()
    {
    }

    /**
     * Test attribute "modified_by"
     */
    public function testPropertyModifiedBy()
    {
    }

    /**
     * Test attribute "subscription"
     */
    public function testPropertySubscription()
    {
    }

    /**
     * Test attribute "term_name"
     */
    public function testPropertyTermName()
    {
    }

    /**
     * Test attribute "ip_address"
     */
    public function testPropertyIpAddress()
    {
    }

    /**
     * Test attribute "in_timeline"
     */
    public function testPropertyInTimeline()
    {
    }
}
