<?php
/**
 * DsFieldDefinitionResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ProfileService\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProfileService-TEST
 *
 * Profile service test
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ProfileService\Client;

/**
 * DsFieldDefinitionResponseTest Class Doc Comment
 *
 * @category    Class
 * @description DsFieldDefinitionResponse
 * @package     ProfileService\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DsFieldDefinitionResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DsFieldDefinitionResponse"
     */
    public function testDsFieldDefinitionResponse()
    {
    }

    /**
     * Test attribute "property_id"
     */
    public function testPropertyPropertyId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "required"
     */
    public function testPropertyRequired()
    {
    }

    /**
     * Test attribute "required_for_offers"
     */
    public function testPropertyRequiredForOffers()
    {
    }

    /**
     * Test attribute "possible_value"
     */
    public function testPropertyPossibleValue()
    {
    }

    /**
     * Test attribute "range_min"
     */
    public function testPropertyRangeMin()
    {
    }

    /**
     * Test attribute "range_max"
     */
    public function testPropertyRangeMax()
    {
    }

    /**
     * Test attribute "range_base_property_id"
     */
    public function testPropertyRangeBasePropertyId()
    {
    }

    /**
     * Test attribute "parent_field_property_id"
     */
    public function testPropertyParentFieldPropertyId()
    {
    }

    /**
     * Test attribute "parent_field_value"
     */
    public function testPropertyParentFieldValue()
    {
    }

    /**
     * Test attribute "readonly"
     */
    public function testPropertyReadonly()
    {
    }
}
