<?php
/**
 * DsOrderItemResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ProfileService\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProfileService-TEST
 *
 * Profile service test
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ProfileService\Client;

/**
 * DsOrderItemResponseTest Class Doc Comment
 *
 * @category    Class
 * @description DsOrderItemResponse
 * @package     ProfileService\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DsOrderItemResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DsOrderItemResponse"
     */
    public function testDsOrderItemResponse()
    {
    }

    /**
     * Test attribute "order_item_number"
     */
    public function testPropertyOrderItemNumber()
    {
    }

    /**
     * Test attribute "parent_order_item_number"
     */
    public function testPropertyParentOrderItemNumber()
    {
    }

    /**
     * Test attribute "order_item_status"
     */
    public function testPropertyOrderItemStatus()
    {
    }

    /**
     * Test attribute "order_item_status_text"
     */
    public function testPropertyOrderItemStatusText()
    {
    }

    /**
     * Test attribute "error_code"
     */
    public function testPropertyErrorCode()
    {
    }

    /**
     * Test attribute "order_quantity"
     */
    public function testPropertyOrderQuantity()
    {
    }

    /**
     * Test attribute "ordered_item"
     */
    public function testPropertyOrderedItem()
    {
    }

    /**
     * Test attribute "order_delivery"
     */
    public function testPropertyOrderDelivery()
    {
    }

    /**
     * Test attribute "order_item_delivery"
     */
    public function testPropertyOrderItemDelivery()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "amount_chf"
     */
    public function testPropertyAmountChf()
    {
    }

    /**
     * Test attribute "tax"
     */
    public function testPropertyTax()
    {
    }

    /**
     * Test attribute "tax_chf"
     */
    public function testPropertyTaxChf()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "ticket"
     */
    public function testPropertyTicket()
    {
    }

    /**
     * Test attribute "offer_bundle_id"
     */
    public function testPropertyOfferBundleId()
    {
    }

    /**
     * Test attribute "additional_property"
     */
    public function testPropertyAdditionalProperty()
    {
    }
}
