<?php
/**
 * DsPartnerDataResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ProfileService\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProfileService-TEST
 *
 * Profile service test
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ProfileService\Client;

/**
 * DsPartnerDataResponseTest Class Doc Comment
 *
 * @category    Class
 * @description DsPartnerDataResponse
 * @package     ProfileService\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DsPartnerDataResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DsPartnerDataResponse"
     */
    public function testDsPartnerDataResponse()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "partner_acronym"
     */
    public function testPropertyPartnerAcronym()
    {
    }

    /**
     * Test attribute "member_id"
     */
    public function testPropertyMemberId()
    {
    }

    /**
     * Test attribute "additional_property"
     */
    public function testPropertyAdditionalProperty()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "data_governance"
     */
    public function testPropertyDataGovernance()
    {
    }

    /**
     * Test attribute "created_date_time"
     */
    public function testPropertyCreatedDateTime()
    {
    }

    /**
     * Test attribute "last_modified"
     */
    public function testPropertyLastModified()
    {
    }

    /**
     * Test attribute "last_modified_by"
     */
    public function testPropertyLastModifiedBy()
    {
    }

    /**
     * Test attribute "created_by_subscription"
     */
    public function testPropertyCreatedBySubscription()
    {
    }

    /**
     * Test attribute "last_modified_by_subscription"
     */
    public function testPropertyLastModifiedBySubscription()
    {
    }
}
