<?php
/**
 * DsStayTravelerRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ProfileService\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProfileService-TEST
 *
 * Profile service
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ProfileService\Client;

use PHPUnit\Framework\TestCase;

/**
 * DsStayTravelerRequestTest Class Doc Comment
 *
 * @category    Class
 * @description DsStayTravelerRequest
 * @package     ProfileService\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DsStayTravelerRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DsStayTravelerRequest"
     */
    public function testDsStayTravelerRequest()
    {
    }

    /**
     * Test attribute "is_customer"
     */
    public function testPropertyIsCustomer()
    {
    }

    /**
     * Test attribute "arrival"
     */
    public function testPropertyArrival()
    {
    }

    /**
     * Test attribute "departure"
     */
    public function testPropertyDeparture()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "identifier"
     */
    public function testPropertyIdentifier()
    {
    }

    /**
     * Test attribute "salutation"
     */
    public function testPropertySalutation()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "given_name"
     */
    public function testPropertyGivenName()
    {
    }

    /**
     * Test attribute "family_name"
     */
    public function testPropertyFamilyName()
    {
    }

    /**
     * Test attribute "birth_date"
     */
    public function testPropertyBirthDate()
    {
    }

    /**
     * Test attribute "nationality"
     */
    public function testPropertyNationality()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "passport"
     */
    public function testPropertyPassport()
    {
    }

    /**
     * Test attribute "reduction"
     */
    public function testPropertyReduction()
    {
    }

    /**
     * Test attribute "additional_property"
     */
    public function testPropertyAdditionalProperty()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "telephone"
     */
    public function testPropertyTelephone()
    {
    }

    /**
     * Test attribute "price_category"
     */
    public function testPropertyPriceCategory()
    {
    }

    /**
     * Test attribute "add_on"
     */
    public function testPropertyAddOn()
    {
    }

    /**
     * Test attribute "profile_image"
     */
    public function testPropertyProfileImage()
    {
    }

    /**
     * Test attribute "supporting_document"
     */
    public function testPropertySupportingDocument()
    {
    }
}
