<?php
/**
 * DsValidateEmailResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ProfileService\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProfileService-TEST
 *
 * Profile service
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ProfileService\Client;

use PHPUnit\Framework\TestCase;

/**
 * DsValidateEmailResponseTest Class Doc Comment
 *
 * @category    Class
 * @description DsValidateEmailResponse
 * @package     ProfileService\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DsValidateEmailResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DsValidateEmailResponse"
     */
    public function testDsValidateEmailResponse()
    {
    }

    /**
     * Test attribute "validation_messages"
     */
    public function testPropertyValidationMessages()
    {
    }

    /**
     * Test attribute "suggestion"
     */
    public function testPropertySuggestion()
    {
    }

    /**
     * Test attribute "is_valid"
     */
    public function testPropertyIsValid()
    {
    }
}
